### PR TITLE
Fix request timeout handling in parser.js

### LINKED ISSUE #238: Socket remains open after a timeout
Node v18.12.1, rss-parser@3.12.0. I am scraping a number of RSS feeds using `rss-parser`. A [Nasdaq feed](https://www.nasdaq.com/feed/rssoutbound?category=Commodities) is invariably giving a timeout after 10 seconds, which is the configured time:

    Could not read https://www.nasdaq.com/feed/rssoutbound?category=Commodities: Request timed out after 10000ms

The feed can be read without issues on a browser so I guess it is limited by user-agent on the server side. Anyway, my program does not terminate properly, and keeps the process open after everything else has been closed. Running it with [wtfnode](https://www.npmjs.com/package/wtfnode) yields the following information:

```
^C[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
- Sockets:
  - 192.168.1.5:41910 -> 23.214.214.41:443
```

As it happens, 23.214.214.41 is (not coincidentally) the IP address of the Nasdaq Akamai endpoint:

```
 $ ping www.nasdaq.com
PING e6982.dsca.akamaiedge.net (23.214.214.41) 56(84) bytes of data.
```

It appears that `rss-parser` is not closing the socket properly after a timeout. Any ideas?

### PR DESCRIPTION
**Pull request by goldsrc**
fixes #238
Memory leak caused by not disposing of the TLS socket in case of timeout.

### CODE REVIEW

**Review by rbren — APPROVED** [review]

File: lib/parser.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ class Parser {
       })
       req.on('error', reject);
       timeout = setTimeout(() => {
-        return reject(new Error("Request timed out after " + this.options.timeout + "ms"));
+        req.destroy(new Error("Request timed out after " + this.options.timeout + "ms"));
```
Comment (rbren) [inline lib/parser.js:121]:
```suggestion
        let err = new Error("Request timed out after " + this.options.timeout + "ms");
        req.destroy(err);
        reject(err);
```

Comment (goldsrc) [reply lib/parser.js]: req.destroy will also call the callback for req.on('error',...) above so no need to reject it sepratly here.
